### ISSUE TITLE
Some function versions are inconsistent between different codes

### ISSUE THREAD

**Issue by xianliuzhen** [bl166/WirelessFL-PDGNet#2]
Thank you very much for your reply and added fedrated.py file! But it looks like you changed the usage of some functions in the previous part of the code. I would really appreciate it if you could update other code to the latest version, such as utils, sysmodels!

**Comment by bl166** [comment]
sorry for the late reply. i am currently working on an extended version of this paper and might have indeed changed some functions here and there.. i will have more time to clean it up once the writing is done. thanks

**Comment by xianliuzhen** [comment]
Thanks for your reply, I have successfully run the code by modifying some functions. At the same time, your code has greatly helped me understand federated learning and graph neural networks!
